//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_skill_level
    {
        public decimal person_dbid { get; set; }
        public decimal skill_dbid { get; set; }
        public Nullable<int> level_ { get; set; }
        public Nullable<decimal> person_csid { get; set; }
        public Nullable<decimal> skill_csid { get; set; }
    }
}
