//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_flex_prop
    {
        public decimal dbid { get; set; }
        public Nullable<decimal> object_dbid { get; set; }
        public Nullable<int> object_type { get; set; }
        public Nullable<decimal> parent_dbid { get; set; }
        public string prop_name { get; set; }
        public string prop_value { get; set; }
        public Nullable<int> prop_type { get; set; }
        public int part { get; set; }
        public Nullable<decimal> csid { get; set; }
        public Nullable<decimal> object_csid { get; set; }
        public Nullable<decimal> parent_csid { get; set; }
    }
}
