//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_dn
    {
        public decimal dbid { get; set; }
        public Nullable<decimal> switch_dbid { get; set; }
        public Nullable<decimal> tenant_dbid { get; set; }
        public Nullable<int> type { get; set; }
        public string number_ { get; set; }
        public string association { get; set; }
        public Nullable<int> login_flag { get; set; }
        public string dn_login_id { get; set; }
        public Nullable<int> register_all { get; set; }
        public Nullable<decimal> group_dbid { get; set; }
        public Nullable<int> trunks { get; set; }
        public Nullable<int> route_type { get; set; }
        public string @override { get; set; }
        public Nullable<int> state { get; set; }
        public string name { get; set; }
        public Nullable<int> use_override { get; set; }
        public Nullable<int> sw_specific_type { get; set; }
        public Nullable<decimal> csid { get; set; }
        public Nullable<decimal> switch_csid { get; set; }
        public Nullable<decimal> tenant_csid { get; set; }
        public Nullable<decimal> group_csid { get; set; }
        public Nullable<decimal> place_dbid { get; set; }
        public Nullable<decimal> place_csid { get; set; }
        public Nullable<decimal> site_dbid { get; set; }
        public Nullable<decimal> contract_dbid { get; set; }
    }
}
