//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_script
    {
        public decimal dbid { get; set; }
        public string name { get; set; }
        public Nullable<decimal> tenant_dbid { get; set; }
        public Nullable<int> index_ { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> cont_person_dbid { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> csid { get; set; }
        public Nullable<decimal> tenant_csid { get; set; }
        public Nullable<decimal> cont_person_csid { get; set; }
    }
}
