//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ivr_sugg_agency
    {
        public string AGENCY_ID { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string AGENCY_NAME { get; set; }
        public string AGENCY_NAME_WAV_FILENAME { get; set; }
        public string AGENCY_COVER_AREA { get; set; }
        public string AGENCY_INFO { get; set; }
        public string FAX_AGENCY_INFO { get; set; }
        public string AGENCY_WAV_FILENAME { get; set; }
        public string VALID { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string CATEGORY { get; set; }
        public string ADD_TYPE { get; set; }
    }
}
