//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_BlackListType
    {
        public SPhone_BlackListType()
        {
            this.SPhone_BlackList = new HashSet<SPhone_BlackList>();
        }
    
        public System.Guid BlackListTypeID { get; set; }
        public string TypeName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<SPhone_BlackList> SPhone_BlackList { get; set; }
    }
}
