//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_ChatTextType
    {
        public SPhone_ChatTextType()
        {
            this.SPhone_ChatText = new HashSet<SPhone_ChatText>();
        }
    
        public System.Guid ChatTextTypeID { get; set; }
        public string ChatTextTypeName { get; set; }
        public Nullable<int> SN { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<SPhone_ChatText> SPhone_ChatText { get; set; }
    }
}
