//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_ReportUrl
    {
        public long ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string ReportName { get; set; }
        public string ReportPath { get; set; }
        public int IsShow { get; set; }
    }
}
