//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_Holiday
    {
        public System.Guid HolidayID { get; set; }
        public Nullable<System.Guid> HolidayRoleID { get; set; }
        public string DNIS { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string TypeName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string QueueName { get; set; }
        public string Q_Name { get; set; }
        public string Q_ProcessingBegin { get; set; }
        public string Q_ProcessingEnd { get; set; }
        public Nullable<int> Q_IsValid { get; set; }
        public Nullable<System.DateTime> Q_RestDate { get; set; }
    
        public virtual SPhone_HolidayRole SPhone_HolidayRole { get; set; }
    }
}
