//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sphone_Call
    {
        public string CallID { get; set; }
        public string EmployeeID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime CallBeginTime { get; set; }
        public Nullable<System.DateTime> CallEndTime { get; set; }
        public Nullable<System.DateTime> DeskTime { get; set; }
        public string ConnectionID { get; set; }
        public Nullable<int> InOut { get; set; }
        public string CurrentQueueName { get; set; }
        public string FromQueueName { get; set; }
        public string NextQueueName { get; set; }
        public string ANI { get; set; }
        public string DNIS { get; set; }
        public string PlaceIP { get; set; }
        public Nullable<int> IsConference { get; set; }
        public Nullable<int> IsTransfer { get; set; }
        public Nullable<int> IsTransferEPOS { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
