//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_Role
    {
        public SPhone_Role()
        {
            this.SPhone_RoleModule = new HashSet<SPhone_RoleModule>();
            this.SPhone_UserPermission = new HashSet<SPhone_UserPermission>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<SPhone_RoleModule> SPhone_RoleModule { get; set; }
        public virtual ICollection<SPhone_UserPermission> SPhone_UserPermission { get; set; }
    }
}
