//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_HolidayRole
    {
        public SPhone_HolidayRole()
        {
            this.SPhone_Holiday = new HashSet<SPhone_Holiday>();
        }
    
        public System.Guid HolidayRoleID { get; set; }
        public string HolidayRoleName { get; set; }
        public Nullable<System.DateTime> HolidayBegin { get; set; }
        public Nullable<System.DateTime> HolidayEnd { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<SPhone_Holiday> SPhone_Holiday { get; set; }
    }
}
