//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPhone_Chat
    {
        public string ChatID { get; set; }
        public string EmployeeID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> ChatBeginTime { get; set; }
        public Nullable<System.DateTime> ChatEndTime { get; set; }
        public string ConnectionID { get; set; }
        public string CurrentQueueName { get; set; }
        public string FromQueueName { get; set; }
        public string NextQueueName { get; set; }
        public string MachineNo { get; set; }
        public string PlaceIP { get; set; }
        public string MailAddress { get; set; }
        public string ContentText { get; set; }
        public Nullable<int> IsConference { get; set; }
        public Nullable<int> IsTransfer { get; set; }
        public Nullable<int> IsRTO { get; set; }
        public string ServicecardNo { get; set; }
        public Nullable<int> WSISID { get; set; }
        public string Enterid { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string CustomerIP { get; set; }
        public string IPLocation { get; set; }
    }
}
