//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tele.ServiceReference.CfgServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EventAuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool EventAuthenticated {
            get {
                return this.EventAuthenticatedField;
            }
            set {
                if ((this.EventAuthenticatedField.Equals(value) != true)) {
                    this.EventAuthenticatedField = value;
                    this.RaisePropertyChanged("EventAuthenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DBIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tele.ServiceReference.CfgServiceReference.AgentInfo AgentInfoField;
        
        private int CHATField;
        
        private int VOICEField;
        
        private System.DateTime LastDateField;
        
        private int LastValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DBID {
            get {
                return this.DBIDField;
            }
            set {
                if ((this.DBIDField.Equals(value) != true)) {
                    this.DBIDField = value;
                    this.RaisePropertyChanged("DBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Tele.ServiceReference.CfgServiceReference.AgentInfo AgentInfo {
            get {
                return this.AgentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentInfoField, value) != true)) {
                    this.AgentInfoField = value;
                    this.RaisePropertyChanged("AgentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CHAT {
            get {
                return this.CHATField;
            }
            set {
                if ((this.CHATField.Equals(value) != true)) {
                    this.CHATField = value;
                    this.RaisePropertyChanged("CHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int VOICE {
            get {
                return this.VOICEField;
            }
            set {
                if ((this.VOICEField.Equals(value) != true)) {
                    this.VOICEField = value;
                    this.RaisePropertyChanged("VOICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime LastDate {
            get {
                return this.LastDateField;
            }
            set {
                if ((this.LastDateField.Equals(value) != true)) {
                    this.LastDateField = value;
                    this.RaisePropertyChanged("LastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int LastValue {
            get {
                return this.LastValueField;
            }
            set {
                if ((this.LastValueField.Equals(value) != true)) {
                    this.LastValueField = value;
                    this.RaisePropertyChanged("LastValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AgentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tele.ServiceReference.CfgServiceReference.SkillLevel[] SkillLevelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tele.ServiceReference.CfgServiceReference.AgentLogin[] AgentLoginsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Tele.ServiceReference.CfgServiceReference.SkillLevel[] SkillLevels {
            get {
                return this.SkillLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillLevelsField, value) != true)) {
                    this.SkillLevelsField = value;
                    this.RaisePropertyChanged("SkillLevels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Tele.ServiceReference.CfgServiceReference.AgentLogin[] AgentLogins {
            get {
                return this.AgentLoginsField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentLoginsField, value) != true)) {
                    this.AgentLoginsField = value;
                    this.RaisePropertyChanged("AgentLogins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillLevel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SkillLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DBIDField;
        
        private int LevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DBID {
            get {
                return this.DBIDField;
            }
            set {
                if ((this.DBIDField.Equals(value) != true)) {
                    this.DBIDField = value;
                    this.RaisePropertyChanged("DBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentLogin", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AgentLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DBIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DBID {
            get {
                return this.DBIDField;
            }
            set {
                if ((this.DBIDField.Equals(value) != true)) {
                    this.DBIDField = value;
                    this.RaisePropertyChanged("DBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginCode {
            get {
                return this.LoginCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginCodeField, value) != true)) {
                    this.LoginCodeField = value;
                    this.RaisePropertyChanged("LoginCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skill", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Skill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DBIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DBID {
            get {
                return this.DBIDField;
            }
            set {
                if ((this.DBIDField.Equals(value) != true)) {
                    this.DBIDField = value;
                    this.RaisePropertyChanged("DBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ObjectPath {
            get {
                return this.ObjectPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectPathField, value) != true)) {
                    this.ObjectPathField = value;
                    this.RaisePropertyChanged("ObjectPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CfgServiceReference.CfgServiceSoap")]
    public interface CfgServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Tele.ServiceReference.CfgServiceReference.HelloWorldResponse HelloWorld(Tele.ServiceReference.CfgServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        Tele.ServiceReference.CfgServiceReference.AuthenticateResponse Authenticate(Tele.ServiceReference.CfgServiceReference.AuthenticateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 employeeId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        Tele.ServiceReference.CfgServiceReference.GetPersonResponse GetPerson(Tele.ServiceReference.CfgServiceReference.GetPersonRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSkillResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSkill", ReplyAction="*")]
        Tele.ServiceReference.CfgServiceReference.GetSkillResponse GetSkill(Tele.ServiceReference.CfgServiceReference.GetSkillRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Tele.ServiceReference.CfgServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Tele.ServiceReference.CfgServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(Tele.ServiceReference.CfgServiceReference.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string userName, string userPassword) {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(Tele.ServiceReference.CfgServiceReference.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tele.ServiceReference.CfgServiceReference.LoginResult AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(Tele.ServiceReference.CfgServiceReference.LoginResult AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(Tele.ServiceReference.CfgServiceReference.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string employeeId;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(string employeeId) {
            this.employeeId = employeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(Tele.ServiceReference.CfgServiceReference.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tele.ServiceReference.CfgServiceReference.Person GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(Tele.ServiceReference.CfgServiceReference.Person GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkill", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.GetSkillRequestBody Body;
        
        public GetSkillRequest() {
        }
        
        public GetSkillRequest(Tele.ServiceReference.CfgServiceReference.GetSkillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSkillRequestBody {
        
        public GetSkillRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkillResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.CfgServiceReference.GetSkillResponseBody Body;
        
        public GetSkillResponse() {
        }
        
        public GetSkillResponse(Tele.ServiceReference.CfgServiceReference.GetSkillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tele.ServiceReference.CfgServiceReference.Skill[] GetSkillResult;
        
        public GetSkillResponseBody() {
        }
        
        public GetSkillResponseBody(Tele.ServiceReference.CfgServiceReference.Skill[] GetSkillResult) {
            this.GetSkillResult = GetSkillResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CfgServiceSoapChannel : Tele.ServiceReference.CfgServiceReference.CfgServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CfgServiceSoapClient : System.ServiceModel.ClientBase<Tele.ServiceReference.CfgServiceReference.CfgServiceSoap>, Tele.ServiceReference.CfgServiceReference.CfgServiceSoap {
        
        public CfgServiceSoapClient() {
        }
        
        public CfgServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CfgServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CfgServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CfgServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tele.ServiceReference.CfgServiceReference.HelloWorldResponse Tele.ServiceReference.CfgServiceReference.CfgServiceSoap.HelloWorld(Tele.ServiceReference.CfgServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Tele.ServiceReference.CfgServiceReference.HelloWorldRequest inValue = new Tele.ServiceReference.CfgServiceReference.HelloWorldRequest();
            inValue.Body = new Tele.ServiceReference.CfgServiceReference.HelloWorldRequestBody();
            Tele.ServiceReference.CfgServiceReference.HelloWorldResponse retVal = ((Tele.ServiceReference.CfgServiceReference.CfgServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tele.ServiceReference.CfgServiceReference.AuthenticateResponse Tele.ServiceReference.CfgServiceReference.CfgServiceSoap.Authenticate(Tele.ServiceReference.CfgServiceReference.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public Tele.ServiceReference.CfgServiceReference.LoginResult Authenticate(string userName, string userPassword) {
            Tele.ServiceReference.CfgServiceReference.AuthenticateRequest inValue = new Tele.ServiceReference.CfgServiceReference.AuthenticateRequest();
            inValue.Body = new Tele.ServiceReference.CfgServiceReference.AuthenticateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            Tele.ServiceReference.CfgServiceReference.AuthenticateResponse retVal = ((Tele.ServiceReference.CfgServiceReference.CfgServiceSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tele.ServiceReference.CfgServiceReference.GetPersonResponse Tele.ServiceReference.CfgServiceReference.CfgServiceSoap.GetPerson(Tele.ServiceReference.CfgServiceReference.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public Tele.ServiceReference.CfgServiceReference.Person GetPerson(string employeeId) {
            Tele.ServiceReference.CfgServiceReference.GetPersonRequest inValue = new Tele.ServiceReference.CfgServiceReference.GetPersonRequest();
            inValue.Body = new Tele.ServiceReference.CfgServiceReference.GetPersonRequestBody();
            inValue.Body.employeeId = employeeId;
            Tele.ServiceReference.CfgServiceReference.GetPersonResponse retVal = ((Tele.ServiceReference.CfgServiceReference.CfgServiceSoap)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tele.ServiceReference.CfgServiceReference.GetSkillResponse Tele.ServiceReference.CfgServiceReference.CfgServiceSoap.GetSkill(Tele.ServiceReference.CfgServiceReference.GetSkillRequest request) {
            return base.Channel.GetSkill(request);
        }
        
        public Tele.ServiceReference.CfgServiceReference.Skill[] GetSkill() {
            Tele.ServiceReference.CfgServiceReference.GetSkillRequest inValue = new Tele.ServiceReference.CfgServiceReference.GetSkillRequest();
            inValue.Body = new Tele.ServiceReference.CfgServiceReference.GetSkillRequestBody();
            Tele.ServiceReference.CfgServiceReference.GetSkillResponse retVal = ((Tele.ServiceReference.CfgServiceReference.CfgServiceSoap)(this)).GetSkill(inValue);
            return retVal.Body.GetSkillResult;
        }
    }
}
