//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tele.ServiceReference.StatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatServiceReference.StatServiceSoap")]
    public interface StatServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Tele.ServiceReference.StatServiceReference.HelloWorldResponse HelloWorld(Tele.ServiceReference.StatServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 EmployeeID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Open12", ReplyAction="*")]
        Tele.ServiceReference.StatServiceReference.Open12Response Open12(Tele.ServiceReference.StatServiceReference.Open12Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get12", ReplyAction="*")]
        int Get12(int DBID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.StatServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Tele.ServiceReference.StatServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.StatServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Tele.ServiceReference.StatServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Open12Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Open12", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.StatServiceReference.Open12RequestBody Body;
        
        public Open12Request() {
        }
        
        public Open12Request(Tele.ServiceReference.StatServiceReference.Open12RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Open12RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DBID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmployeeID;
        
        public Open12RequestBody() {
        }
        
        public Open12RequestBody(int DBID, string EmployeeID) {
            this.DBID = DBID;
            this.EmployeeID = EmployeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Open12Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Open12Response", Namespace="http://tempuri.org/", Order=0)]
        public Tele.ServiceReference.StatServiceReference.Open12ResponseBody Body;
        
        public Open12Response() {
        }
        
        public Open12Response(Tele.ServiceReference.StatServiceReference.Open12ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Open12ResponseBody {
        
        public Open12ResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatServiceSoapChannel : Tele.ServiceReference.StatServiceReference.StatServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatServiceSoapClient : System.ServiceModel.ClientBase<Tele.ServiceReference.StatServiceReference.StatServiceSoap>, Tele.ServiceReference.StatServiceReference.StatServiceSoap {
        
        public StatServiceSoapClient() {
        }
        
        public StatServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tele.ServiceReference.StatServiceReference.HelloWorldResponse Tele.ServiceReference.StatServiceReference.StatServiceSoap.HelloWorld(Tele.ServiceReference.StatServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Tele.ServiceReference.StatServiceReference.HelloWorldRequest inValue = new Tele.ServiceReference.StatServiceReference.HelloWorldRequest();
            inValue.Body = new Tele.ServiceReference.StatServiceReference.HelloWorldRequestBody();
            Tele.ServiceReference.StatServiceReference.HelloWorldResponse retVal = ((Tele.ServiceReference.StatServiceReference.StatServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tele.ServiceReference.StatServiceReference.Open12Response Tele.ServiceReference.StatServiceReference.StatServiceSoap.Open12(Tele.ServiceReference.StatServiceReference.Open12Request request) {
            return base.Channel.Open12(request);
        }
        
        public void Open12(int DBID, string EmployeeID) {
            Tele.ServiceReference.StatServiceReference.Open12Request inValue = new Tele.ServiceReference.StatServiceReference.Open12Request();
            inValue.Body = new Tele.ServiceReference.StatServiceReference.Open12RequestBody();
            inValue.Body.DBID = DBID;
            inValue.Body.EmployeeID = EmployeeID;
            Tele.ServiceReference.StatServiceReference.Open12Response retVal = ((Tele.ServiceReference.StatServiceReference.StatServiceSoap)(this)).Open12(inValue);
        }
        
        public int Get12(int DBID) {
            return base.Channel.Get12(DBID);
        }
    }
}
